# Generated by Django 4.0.3 on 2022-04-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tarefa_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='usuario',
            new_name='usuario1',
        ),
    ]
